### ISSUE TITLE
Error in Constructor

### ISSUE THREAD

**Issue by JorgeLL1729** [quaquel/pyNetLogo#66] opened 2023-02-09 10:04 UTC
I am using the package with success and currently trying to move to a parallel implementation (pretty much the ipyparallel example in the documentation) for research in academia.
I am experiencing the following issue:
 When using:
netlogo = pyNetLogo.NetLogoLink(gui=False)
It always appears the following error message:
![image](https://user-images.githubusercontent.com/124350703/217779908-83b19082-e9da-4feb-90c4-cd5f6d9275ca.png)

I have not been able to supress it and when running parallel NetLogoexperiments it basically ruins it since it is needed to click the OK button.

Is there any recommendations or something I need to have installed or any plan to remove the error message?
Thanks! 
Jorge

**Comment by quaquel** [comment] 2023-02-09 10:26
Which version of netlogo are you using?

**Comment by JorgeLL1729** [comment] 2023-02-09 10:30
NetLogo 6.2.0

**Comment by quaquel** [comment] 2023-02-09 10:32
Are you critically dependent on 6.2, or would 6.1 be fine as well?

My hunch is that some things have changed in 6.2 which warrants changes in pynetlogo. I at the moment don't have the time to look into this.

**Comment by JorgeLL1729** [comment] 2023-02-09 10:37
I will try with 6.1
I am using the GIS package but I don't think it will be a problem. I will check during the day.
Thanks a lot.

**Comment by quaquel** [comment] 2023-02-09 10:46
please keep me posted on how you get on. I'll do my best to find time soon to look into this if you need it.

**Comment by JorgeLL1729** [comment] 2023-02-09 11:03
Same behaviour with 6.1 :(
I have not tried with 6.3 though...

**Comment by quaquel** [comment] 2023-02-09 11:15
hmmmm, strange. This suggests to me that it might be related to the GIS package.

**Comment by JorgeLL1729** [comment] 2023-02-09 11:21
I will do this. Since for what I want to do with Python and Netlogo I do not need the GUI, I will try to extract the altitudes, then use them without the GIS package somehow and try again. If the error is not shown anymore we found the issue.

**Comment by EwoutH** [comment] 2023-03-07 17:59
@JorgeLL1729 I can confirm my issue (using NetLogo 6.3.0 on Windows, PyNetLogo git master), both with models using and don't using the GIS extension.

Model that uses the GIS extensions:
![Screenshot_98](https://user-images.githubusercontent.com/15776622/223506799-01147c89-d5e3-4669-8bf4-445bd99dadeb.png)

Model that doesn't use the GIS extension:
![Screenshot_99](https://user-images.githubusercontent.com/15776622/223506810-9578b7f3-792d-4b3c-92df-d2164fac9f1d.png)

I believe it has to do with the Java itself, and specifically [JEP 411: Deprecate the Security Manager for Removal](https://openjdk.org/jeps/411). NetLogo 17 bundled a newer Java version with it, upgrading from Java 8 to Java 17. But I believe you have had this issue with NetLogo 6.1 and 6.2 already.

Might you be able which Java version you were using? If you were using any other version than the packaged one it might explain a lot. I believe you can find the Java version PyNetLogo uses by running
```Python
import os
print(os.environ["JAVA_HOME"])
```
from the same Python script you are running PyNetLogo in.

**Comment by EwoutH** [comment] 2023-03-07 18:11
@quaquel I think the issue is with this part of our `NetLogoLink.java`.

https://github.com/quaquel/pyNetLogo/blob/ac2aa6eb102a592c81bfdff9448c06e872349526/pyNetLogo/java/NetLogoLinkV61/NetLogoLink.java#L28-L48

Now that the security manager is deprecated in Java 17 we should migrate to something else, or remove it if it wasn't critical (I don't know).

As for to how to replace it ChatGPT, provides the following response:

<details><summary>
I'm using the Java Security Manager in a project, but that's now deprecated in JEP 411. What is the recommended way to migrate away from it?</summary>

> Yes, you're correct that the Java Security Manager has been deprecated since JDK 17 and may be removed in a future release. If you're using the Java Security Manager in your project, you may need to migrate to a new security mechanism.
> 
> Here are a few options for migrating away from the Java Security Manager:
> 
> 1. Use a Security Provider: One of the alternatives to the Java Security Manager is to use a Security Provider. A Security Provider is a pluggable security module that can be installed and configured at runtime to provide security services. You can use the Java Cryptography Extension (JCE) to add a security provider to your application.
> 
> 2. Use Java Security API: You can also use the Java Security API to perform various security operations in your application. This API provides a set of classes and interfaces for implementing security functionality.
> 
> 3. Use Java Authentication and Authorization Service (JAAS): Java Authentication and Authorization Service (JAAS) is another option for managing security in Java applications. JAAS provides a framework for authentication and authorization.
> 
> 4. Use Security Frameworks: There are also several security frameworks available that can be used to implement security features in your application. Some of the popular security frameworks are Spring Security, Apache Shiro, and OWASP ESAPI.
> 
> When migrating away from the Java Security Manager, you should carefully evaluate the security requirements of your application and choose an appropriate security mechanism that meets your needs.</details>

**Comment by quaquel** [comment] 2023-03-07 18:36
This code follows the mathemtica and R links for NetLogo. Would be good to check what they have done.

**Comment by EwoutH** [comment] 2023-03-07 19:55
Only thing I could find that mentioned the `SecurityManager` was this commit: https://github.com/NetLogo/Palette-Extension/commit/bd2f8e889afec406b01728b62d587469dd1839f9

**Comment by quaquel** [comment] 2023-03-07 20:01
so they fixed it by removing the dependency.

**Comment by quaquel** [comment] 2023-03-08 00:01
Also checked the [mathematica link](https://github.com/NetLogo/Mathematica-Link/blob/master/src/main/NLink.java). No security manager there either. Seems to have been removed quite a while ago because the latest commits to this are from 2 years ago.

**Comment by JorgeLL1729** [comment] 2023-03-08 07:50
Hi! I am using Java 19

**Comment by EwoutH** [comment] 2023-03-08 09:12
Thanks for confirming, this makes it clearly a Java 17+ issue.

I don’t know enough about Java or our implementation (and why it was added in the first place) to say if it can be removed without issue or not.

**Comment by quaquel** [comment] 2023-03-08 18:03
I can figure it out, but given that the other links for NetLogo have removed it, we should also be fine.

For reference, the java code in pynetlogo is a fork of the mathematical link (by now a 10+ year-old fork but still). 

The real challenge is to see if I can move the release process of pynetlogo into a GitHub action. It's a bit involved because you first need to build the jar, and then include this in the files as part of building the python release.

**Comment by quaquel** [comment] 2023-03-09 09:41
Made some progress on this. I have moved pynetlogo to using a pyproject.toml. I also started to setup a ci github action. I successfully installed netlogo 6.3 as part of this. In principle, it should be possible to expand this to build the various jars against netlogo, test the resulting code. and automate release.

**Comment by quaquel** [comment] 2023-03-10 02:49
With commit https://github.com/quaquel/pyNetLogo/commit/50185f2bf114ccdac8ac074a8732bb2bc870c06a, The latest version on master has been tested to work with java 19 on NetLogo 6.3 on an m1 mac.

**Comment by EwoutH** [comment] 2023-03-10 11:36
Awesome! @JorgeLL1729 could you test if this works for you? You can install this latest version using pip, with:

```
pip install -U -e git+https://github.com/quaquel/pyNetLogo@master#egg=pynetlogo
```

**Comment by JorgeLL1729** [comment] 2023-03-13 09:27
Hi,
It seems that either I did something wrong or something is not working properly for me:
I managed to install using pip:

_"Successfully built pynetlogo
Installing collected packages: pynetlogo
  Attempting uninstall: pynetlogo
    Found existing installation: pyNetLogo 0.4.2
    Uninstalling pyNetLogo-0.4.2:
      Successfully uninstalled pyNetLogo-0.4.2
Successfully installed pynetlogo-0.5"_

Then in the folder with packages (see image below) there's only the folder "pynetlogo-0.5.dist-info". I am not a Python expert, but I am assuming I am missing a "pynetlogo" folder? Because I get the following errors:

_import pyNetLogo
ModuleNotFoundError: No module named 'pyNetLogo'_

and 

_import pynetlogo
ModuleNotFoundError: No module named 'pynetlogo'_

Thank you SO much for the effort! Do let me know if I can test something else or assist somehow :)
![image](https://user-images.githubusercontent.com/124350703/224659189-d7520569-00f0-4bc5-a77e-ec1248f7bfec.png)

**Comment by EwoutH** [comment] 2023-03-13 12:15
Which Python version are you using and what's the version of your _setuptools_ package?

**Comment by JorgeLL1729** [comment] 2023-03-13 13:32
python 3.11.0
setuptools 65.5.0

**Comment by EwoutH** [comment] 2023-03-13 13:49
Strange. I installed it with `pip install -U -e git+https://github.com/quaquel/pyNetLogo@master#egg=pynetlogo` and it installed fine (also on Python 3.11).

![image](https://user-images.githubusercontent.com/15776622/224720718-3753c914-e081-47a4-9c01-b446f7d737c0.png)

Could you try updating your setuptools version to the latest version?

**Comment by JorgeLL1729** [comment] 2023-03-13 14:22
Hi again.
I went into the file "direct_url.json"
{"dir_info": {"editable": true}, "url": "file:///C:/SomeFolder/src/pynetlogo"}

I copy-pasted then the pynetlogo folder into the folder where my packages have been installed:
C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages

Now it works when I import it, although the former functions don't work:
"AttributeError: module 'pynetlogo' has no attribute 'NetLogoLink'"

But one step at a time, now after moving it, importing works. Let me know how I could assist now :)

**Comment by EwoutH** [comment] 2023-03-13 16:44
There is another way: Since very recently there are pre-built wheels of development version available. If you go to any [Build distribution](https://github.com/quaquel/pyNetLogo/actions/workflows/release.yml) workflow run with a green checkmark, you will find a _package_ file there. That file contains a pre-built wheel, called `pynetlogo-0.5-py3-none-any.whl`. If you copy that to a convenient folder and do `pip install -U pynetlogo-0.5-py3-none-any.whl` PyNetLogo should install correctly.

**Comment by JorgeLL1729** [comment] 2023-03-13 22:37
Done it.

With 6.1 it works but still get the message:
![image](https://user-images.githubusercontent.com/124350703/224847676-c6d27896-315b-47f8-af1a-6f2019f74bfc.png)

6.3 seems to still give me errors:
_"TypeError: Class NetLogoLinkV63.NetLogoLink is not found"_

The package I dowloaded came from this distribution:
![image](https://user-images.githubusercontent.com/124350703/224847996-1929c3dc-60f3-4a1e-9ee4-6b402026d14d.png)

**Comment by quaquel** [comment] 2023-03-14 02:01
The 6.1 error is related to whatever java version you have installed. It seems jpype is defaulting to a java 17 or newer. You can check this yourself:

```python

import jpype
print(jpype.getDefaultJVMPath())

```

If you want to use 6.1, you need to use an older version of java. You can specify which jvm to use with pynetlogo using the jvm_path keyword argument.

Not sure what is up with 6.3. I checked, and the relevant files are all there. It might be jvm related, so once you try the above code, let me know which version of java you have.

**Comment by JorgeLL1729** [comment] 2023-03-14 09:36
Hi again.
After checking with "print(jpype.getDefaultJVMPath())":
_C:\Program Files\Java\jdk-19\bin\server\jvm.dll_

I want 6.3 if possible. I have seen increased performance in my models and it is my preference rather than 6.1 :)

Again, thanks a lot for the help and time to both!

**Comment by quaquel** [comment] 2023-03-14 18:37
I have no clear idea what is causing your problem. You are on Windows, with java 19. @EwoutH  has successfully used the latest version of pynetlogo on windows with NetLogo 6.3 and java 19.  So something is going on in how you are installing everything. 

Can you give a detailed breakdown of how you do a clean install of pynetlogo?

**Comment by JorgeLL1729** [comment] 2023-03-14 23:20
Hi,
I will do a clean install and share the steps. Meanwhile, here is the error I am getting in detail in case it can give a hint:

_Warning (from warnings module):
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynetlogo\core.py", line 265
    warnings.warn(
UserWarning: could not find default NetLogo extensions folder. Extensions not available
Traceback (most recent call last):
  File "C:\Path1\Path2\Path2\MyFile.py", line 21, in <module>
    netlogo = pynetlogo.NetLogoLink()
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynetlogo\core.py", line 279, in __init__
    link = jpype.JClass(class_name[self.netlogo_version])
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\jpype\_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
TypeError: Class NetLogoLinkV63.NetLogoLink is not found_

**Comment by JorgeLL1729** [comment] 2023-03-16 09:22
Hello again.
I followed the following process:
1) Uninstall as follows:
I have a small script to install/uninstall (C:/Folder/MyInstaller.py)
```
import sys
import runpy
sys.argv=["pip", "uninstall","pynetlogo"]
runpy.run_module("pip", run_name="__main__")
```

2) In that folder, I added the "pynetlogo-0.5-py3-none-any.whl" file.
3) I run then the following with the aforementioned script:
```
import sys
import runpy
sys.argv=["pip", "install", "-U", "pynetlogo-0.5-py3-none-any.whl"]
runpy.run_module("pip", run_name="__main__")
```
With the following output:
```
Processing c:\Folder\pynetlogo-0.5-py3-none-any.whl
Requirement already satisfied: pandas in c:\users\UserID\appdata\roaming\python\python311\site-packages (from pynetlogo==0.5) (1.5.1)
Requirement already satisfied: numpy in c:\users\UserID\appdata\roaming\python\python311\site-packages (from pynetlogo==0.5) (1.23.4)
Requirement already satisfied: jpype1 in c:\users\UserID\appdata\local\programs\python\python311\lib\site-packages (from pynetlogo==0.5) (1.4.1)
Requirement already satisfied: packaging in c:\users\UserID\appdata\roaming\python\python311\site-packages (from jpype1->pynetlogo==0.5) (21.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\UserID\jorlo28\appdata\roaming\python\python311\site-packages (from pandas->pynetlogo==0.5) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\UserID\appdata\roaming\python\python311\site-packages (from pandas->pynetlogo==0.5) (2022.6)
Requirement already satisfied: six>=1.5 in c:\users\UserID\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.1->pandas->pynetlogo==0.5) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\UserID\appdata\roaming\python\python311\site-packages (from packaging->jpype1->pynetlogo==0.5) (3.0.9)
Installing collected packages: pynetlogo
Successfully installed pynetlogo-0.5
```

4) Then I run the following:
```
import pynetlogo
netlogo = pynetlogo.NetLogoLink()
netlogo.load_model('C:/Folder/Netlogo models/MyABS.nlogo')
```
Resulting in the following output ():
```
Warning (from warnings module):
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynetlogo\core.py", line 265
    warnings.warn(
UserWarning: could not find default NetLogo extensions folder. Extensions not available
Traceback (most recent call last):
  File "C:/Folder/Folder1/Folder2/MyABS.py", line 2, in <module>
    netlogo = pynetlogo.NetLogoLink()
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\pynetlogo\core.py", line 279, in __init__
    link = jpype.JClass(class_name[self.netlogo_version])
  File "C:\Users\UserID\AppData\Local\Programs\Python\Python311\Lib\site-packages\jpype\_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
TypeError: Class NetLogoLinkV63.NetLogoLink is not found
```

As I mentioned, I install packages as shown due to the restrictions of administrator privileges, but I don't remember issues with other packages. Also, in the computer coexist older Python releases in case something could become confusing or messy. 
This is all the info I could think of as relevant. I would gladly assist with whatever might be convenient. Thanks a lot for the help (and sorry about the headaches...)

**Comment by quaquel** [comment] 2023-03-19 17:59
I find it difficult to guess what is going on. I will look into trying to make the TypeError a bit more informative, but that might take some time. 

Looking at your print statement, It seems that you python in the output has a different location then where you install pynetlogo:

`C:\Users\UserID\AppData\Local\Programs\Python\Python311` versus `c:\users\UserID\appdata\roaming\python\python311`

Another guess: which java version are you using?

**Comment by JorgeLL1729** [comment] 2023-03-20 08:37
Oh good eye. I will look into that.

After checking with "print(jpype.getDefaultJVMPath())":
C:\Program Files\Java\jdk-19\bin\server\jvm.dll

**Comment by EwoutH** [comment] 2023-03-20 08:51
Something else entirely: You can also try using Java version that is shipped with NetLogo. You can do that by setting the `JAVA_HOME` environment variable.

```Python
import os
os.environ["JAVA_HOME"] = 'C:/Program Files/NetLogo 6.3.0/runtime/bin/server/'
```

**Comment by JorgeLL1729** [comment] 2023-03-20 08:54
Ok! Meanwhile I have noticed this:
![image](https://user-images.githubusercontent.com/124350703/226290746-78eb0800-75fa-40b1-8bf5-dfe42c79c5cd.png)
while
![image](https://user-images.githubusercontent.com/124350703/226290872-9c26f930-7912-4f2e-bfbb-4dfe9430ef2b.png)

**Comment by quaquel** [comment] 2023-03-20 09:45
.class files are like .pyc files. Basically, compiled versions are created when making the .jar file. The .jar file is like a python module. Can you show what is available in the java folder itself?

**Comment by JorgeLL1729** [comment] 2023-03-20 10:24
Hi:
This didn't work:
```
import os
os.environ["JAVA_HOME"] = 'C:/Program Files/NetLogo 6.3.0/runtime/bin/server/'
```
Regarding the java folder:
![image](https://user-images.githubusercontent.com/124350703/226311687-30b850b7-c9f8-467d-8015-252bf2dd5933.png)
Then for all except 6.3:
![image](https://user-images.githubusercontent.com/124350703/226311960-d6d23113-f629-4ce7-a9b6-a50bedfdb527.png)
Inside 6.3:
![image](https://user-images.githubusercontent.com/124350703/226312136-48c9631e-ca32-49a2-aa07-f9546cb1ea4c.png)

**Comment by quaquel** [comment] 2023-03-21 06:54
I pushed a new version of the jar with various other changes as well. I have tested this commit under windows and m1 mac. Could you try to see if it works for you as well?

Under windows, I tested it with the JVM that shipped with netlogo itself. so

```python
import pynetlogo

jvm_path = 'C:/Program Files/NetLogo 6.3.0/runtime/bin/server/jvm.dll
link = pynetlogo.NetLogoLink(jvm_path=jvm_path)

```

**Comment by quaquel** [comment] 2023-03-22 14:22
version 0.5 is now available through PyPi. I am closing this issue but feel free to restart the question if you still need help.

**Closed by quaquel** 2023-03-22 14:22 UTC
Labels: bug
