### ISSUE TITLE
Reporting a 3D list from netlogo gives error

### ISSUE THREAD

**Issue by NedaMarvasti** [quaquel/pyNetLogo#25] opened 2019-08-06 14:23 UTC
I  want to report a 3D list from NetLogo in python using pyNetLogo.

I am running a NetLogo model with "n" turtles. Each day turtles investigate the world and generate 8 values which I save in a list named 'today-value' and I keep a list of list 'turtle-table-daily' to keep values of all days of each turtle.

initialisation:
set turtle-table-daily (list 0 0 0 0 0 0 0 0)

and in each day:
set turtle-table-daily lput today-value turtle-table-daily

So after "K" days, for each agent I have a K*8 list.

I want to report a list where each row of it is 'turtle-table-daily' of one turtle. Here is what I did:

to create-output-table                          
  let X count turtles                            
  set global-table-daily n-values X [0]   

  let i 0
   while [ i < X ] [
    ask turtles with [who = i] [
      set global-table-daily replace-item i global-table-daily turtle-table-daily 
    set i i + 1
  ]]
end

to-report tableGlobal
  report global-table-daily
end

So, global-table-daily is a list of n*K*8.

Finally, in python, I call NetLogo using pyNetLogo and after running the model I ask for reporting tableGlobal:

netlogo.report('tableGlobal')
But I get the following error: 'NetLogoLinkV6.NLResult' object is not iterable

Any help?

**Comment by quaquel** [comment] 2019-08-13 08:49
do you have a more complete stack trace? My guess is that this error comes from the attempted automatic conversion of java datatypes to python datatypes.

**Comment by NedaMarvasti** [comment] 2019-08-13 13:41
Hi Thanks for your answer, 

The Netlogo output for n=3 agent, K=3 days and 8 variables is 
[[[0 0 2 4 6 0 4 0][0 0 1 0 3 1 0 0][1 0 2 0 3 4 4 5]]
[[0 0 0 1 0 0 0 1][0 0 1 0 0 1 0 1 ][1 0 2 2 0 3 0 0 ]]
[[0 0 0 0 0 0 0 0][0 0 1 0 1 0 0 1][1 0 2 0 3 3 1 0]]]

I am trying to read this by pyNetLogo and get this trace of errors:
========================================================
NetLogoException                          Traceback (most recent call last)
~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in _cast_results(self, results)
    671         try:
--> 672             converted_results = type_convert(results)
    673         except:

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in type_convert(results)
    715     else:
--> 716         raise NetLogoException("Unknown datatype")

NetLogoException: Unknown datatype

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-5-e0a92f861aab> in <module>()
----> 1 netlogo.report('tableGlobal')

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in report(self, netlogo_reporter)
    332         try:
    333             result = self.link.report(netlogo_reporter)
--> 334             return self._cast_results(result)
    335         except jpype.JavaException as ex:
    336             raise NetLogoException(ex.message())

~/.local/lib/python3.6/site-packages/pyNetLogo/core.py in _cast_results(self, results)
    673         except:
    674             converted_results=[]
--> 675             for i in results:
    676                 converted_results.append(type_convert(i))
    677 

TypeError: 'NetLogoLinkV6.NLResult' object is not iterable
===========================================
I guess since there is no "," between numbers in NetLogo format, Python can not recognise it.
But how can I solve this?

**Comment by quaquel** [comment] 2019-08-13 13:57
no, the problem is not with the netlogo strings. What is happening is that the netlogo data structure is converted into a java structure, which I then have to convert to a python structure. It seems that your example breaks the python code. 

Which version of pynetlogo do you use? (print(pynetlogo.__version__))
Which version of netlogo do you use?
Could you share your example that creates the error?

I am working on fixing #24, I might be able to fix this at the same time and create a new release of pynetlogo this month.

**Comment by NedaMarvasti** [comment] 2019-08-13 16:07
Great! Thanks. 

pynetlogo: 0.3
netlogo:6.0.4
and here is an example of what I want to do:

[test1.nlogo.zip](https://github.com/quaquel/pyNetLogo/files/3497844/test1.nlogo.zip)

**Comment by quaquel** [comment] 2019-08-14 12:08
It seems that this error has already been fixed with version 0.3.1, so can you try updating pynetlogo (```pip install pynetlogo -U```)

something else, it is often useful to provide a minimum working example with the error. In your case, you have extensions that caused problems for me and the relevant python code was also missing. I could easily fix it in this case so it was not a major problem.

**Comment by quaquel** [comment] 2019-08-14 13:28
it seems I never released 3.1 on pip. I will provide a new release as soon as possible which should fix your problem.

**Comment by NedaMarvasti** [comment] 2019-08-14 16:18
> It seems that this error has already been fixed with version 0.3.1, so can you try updating pynetlogo (`pip install pynetlogo -U`)
> 
> something else, it is often useful to provide a minimum working example with the error. In your case, you have extensions that caused problems for me and the relevant python code was also missing. I could easily fix it in this case so it was not a major problem.

Sure, thanks.

> it seems I never released 3.1 on pip. I will provide a new release as soon as possible which should fix your problem.

Thanks.

**Comment by quaquel** [comment] 2019-08-22 11:32
quick update: jpype has moved to version 0.7 with a few API breaking changes. I am currently trying to address these in the new release as well which is delaying the new release. I still aim to finish it this month.

**Comment by quaquel** [comment] 2019-08-26 09:15
version 0.4 of pynetlogo is available. It should fix your problem.

Note that it requires the latest version of jpype (0.7).

**Closed by quaquel** 2019-08-26 09:15 UTC
