### ISSUE TITLE
Cannot run after pack model via Pyinstaller 

### ISSUE THREAD

**Issue by Westlife1002** [quaquel/pyNetLogo#17] opened 2019-01-04 06:02 UTC
I was trying to pack a PyNetlogo based python program into a .exe file via pyinstaller. When I run the python program in pycharm it works and interacts with netlogo model without any problem. However, when I packed it into .exe file it reported error: 
"pype._jexception.java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class NetLogoLinkV6.NetLogoLink not found"

I guess it has some issues with java_home path. I have corrected the path but I still encounter with such error message. What is the root cause and how to fix? I installed Jpype using whl file: JPype1-0.6.3-cp36-cp36m-win_amd64.whl. My operating system is windows 10 64 bits.

Many thanks for the clarification.

**Comment by quaquel** [comment] 2019-01-04 13:20
I had a quick look at the documentation of pyinstaller since I have never used this myself. It seems you need to specify any additional files explicitly, see https://pyinstaller.readthedocs.io/en/stable/operating-mode.html. For pynetlogo, this means you need to specify the absolute path to ./pynetlogo/java/netlogolink.jar. I hope this helps.

**Comment by Westlife1002** [comment] 2019-01-04 13:41
Dear Jan,

I am testing with your example model "wolf and sheep". (see attachd)
I have problem to pip install Jpype so I installed it via whl. I can run the python program and output results via Pycharm. After Pyinstall, it reports "pype._jexception.java.lang.RuntimeExceptionPyRaisable: java.lang.RuntimeException: Class NetLogoLinkV6.NetLogoLink not found"

You can test pyinstalling:
pyinstaller -F PyNetlogo.py

thank you for your help.

Best,
Jie

________________________________

**Comment by quaquel** [comment] 2019-01-04 13:43
As I indicated above, the problem is that the netloglink.jar file is not included in the exe that you create through pyinstall. You need to explicitly tell pyinstall to do so, for details see the provided link to the documentation of pyinstall.

**Comment by Westlife1002** [comment] 2019-01-04 13:45
Where is netloglink.jar located?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by quaquel** [comment] 2019-01-04 13:49
See my first answer: it is in the directory where pynetlogo is installed, so most likely something like <python directory>/site-packages/pynetlogo/java/netlogolink.jar

**Comment by Westlife1002** [comment] 2019-01-05 20:45
I have told pyinstaller to include netlogolink.jar during the installing process (see attached pic)
![6](https://user-images.githubusercontent.com/34776946/50729019-c1ada180-116d-11e9-8323-1c9955988b09.png)
I still get error message as below:
![7](https://user-images.githubusercontent.com/34776946/50729024-cffbbd80-116d-11e9-8c36-4e0305f74412.png)

**Comment by Westlife1002** [comment] 2019-01-05 21:41
tried all files in folder NetlogoLinkV6 with no success. 

pyinstaller -F --paths=C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NetLogoLink.class;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NetLogoLink$1.class;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NetLogoLink$2.class;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NetLogoLink$3.class;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NetLogoLink.java;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NLResult.class;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\NetLogoLinkV6\NLResult.java;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\.classpath;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink\.project;C:\Users\Jie\AppData\Local\Programs\Python\Python36\Lib\site-packages\pyNetLogo\java\netlogolink.jar PyNetlogo.py

which file actually refers to "Class NetlogoLinkV6.NetlogoLink" which is reported "not found"

**Comment by quaquel** [comment] 2019-01-07 10:55
can you check the following:

```python
import os

print(pynetlogo.PYNETLOGO_HOME)

print(os.path.exists(os.path.join(pynetlogo.PYNETLOGO_HOME, 'java', 'netlogolink.jar')

```

probably include this at the start of the python file that you are using for your code in the executable. I need to know if the assumed path for netlogolink.jar actually exists.

**Comment by Westlife1002** [comment] 2019-01-07 11:55
Hi Jan,

It’s reporting “AttributeError: module 'pyNetLogo' has no attribute 'PYNETLOGO_HOME'”
I attach the test file(Check.py) and the full file for building the .exe (Wolf Sheep Predation_v6.py) for you to check.


________________________________

**Comment by quaquel** [comment] 2019-01-07 11:59
change it to pyNetLogo.core.PYNETLOGO_HOME in both places

**Comment by Westlife1002** [comment] 2019-01-07 12:01
Now it returns “True”


________________________________

**Comment by quaquel** [comment] 2019-01-07 12:02
is this after packaging with pyinstaller?

**Comment by Westlife1002** [comment] 2019-01-07 12:14
After packing with pyinstaller, it reported the same problem as before.

Is there other ways to pack the file which can be working fine with the .jar file?

**Comment by quaquel** [comment] 2019-01-07 12:16
that is not my question. Does the above code return true or false after packaging?

**Comment by quaquel** [comment] 2019-01-07 12:19
ok, so even if the jar is included in the exe, it is not located where pynetlogo expects it. That is, something is still not right with how pynetlogo.jar is included by pyinstaller. I have no idea how pyinstaller works, so this is very hard for me to debug.

**Comment by Westlife1002** [comment] 2019-01-07 12:21
Are there other solutions to pack the file rather than using pyinstaller which can be working?

**Comment by quaquel** [comment] 2019-01-07 12:23
I have never used packaging into executables so I have no idea.

**Comment by Westlife1002** [comment] 2019-01-07 12:30
This is all I got
[cid:image003.png@01D4A6C7.D515B7A0]

Can you tell me what file or files are specifically required here? Pyinstaller has –add-data option to include additional files when bundling the .exe

If this is not gonna be working in any way, are there any alternative libraries which does the same work to allow me control netlogo model from python script?


________________________________

**Comment by quaquel** [comment] 2019-01-07 12:36
As stated above, pynetlogo needs netlogolink.jar. The problem seems to be that pyinstaller is placing this file in a different location than the one expected by pynetlogo. Resolving this requires 2 things:

1. where does pynetlogo think the file is? For this Could you run the first print line of the above code after packaging?
2. Where does pyinstaller actually place the file? No idea yet how to figure this out. Seems like pyinstaller creates a directory, so probably do a search on the directory to figure out the location.

**Comment by Westlife1002** [comment] 2019-01-07 13:16
As you could see from below picture, after packing the file is at: C:\Users\Jie\AppData\Local\Temp\_MEI78242\pyNetLogo
[cid:image003.png@01D4A6CE.4BE0BB40]


In Pycharm which is working fine, the file is at:
C:\Users\Jie\AppData\Local\Programs\Python\Python36\lib\site-packages\pyNetLogo
[cid:image005.png@01D4A6CE.4BE0BB40]

**Comment by Westlife1002** [comment] 2019-01-07 13:36
Answer to your first question. Pictures attached.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Zhu Jie <jess.zhu@hotmail.com>
Sent: Monday, January 7, 2019 9:16:49 PM
To: quaquel/pyNetLogo
Subject: RE: [quaquel/pyNetLogo] Cannot run after pack model via Pyinstaller (#17)

As you could see from below picture, after packing the file is at: C:\Users\Jie\AppData\Local\Temp\_MEI78242\pyNetLogo
[cid:image003.png@01D4A6CE.4BE0BB40]


In Pycharm which is working fine, the file is at:
C:\Users\Jie\AppData\Local\Programs\Python\Python36\lib\site-packages\pyNetLogo
[cid:image005.png@01D4A6CE.4BE0BB40]

**Comment by Westlife1002** [comment] 2019-01-07 14:12
1). Before packing, the script is run in Pycharm which is working fine, the .jar file is at:
C:\Users\Jie\AppData\Local\Programs\Python\Python36\lib\site-packages\pyNetLogo
![3](https://user-images.githubusercontent.com/34776946/50772595-4a8d2000-12c9-11e9-8f7c-bc0cacd366f9.png)

2). After packing, the file is at: C:\Users\Jie\AppData\Local\Temp_MEI78242\pyNetLogo
![1](https://user-images.githubusercontent.com/34776946/50772604-50830100-12c9-11e9-88d1-bd4b22cffc40.png)

**Comment by quaquel** [comment] 2019-01-07 14:14
Please post the pictures on github, rather than attaching them to your e-mail reply. 

So, we now know where pynetlogo expect the file to be. Clearly it is not there (the False from the earlier print statement). So, next up is figuring out where pyinstaller put the file. 

How exactly are you using pyinstaller. Are you bundling to a single directory? If so, what does the content of this directory look like?

**Comment by quaquel** [comment] 2019-01-07 15:30
I am on a mac, so I can't use pypinstaller. 

However, get rid of the -F tag. As stated explicitly in the pyinstaller documentation, debugging is easier if you turn it into a directory structure rather than a single file.

**Comment by Westlife1002** [comment] 2019-01-07 15:39
tried again without -F. It ouputs two folders: dist and build. this is how they look like:
![8](https://user-images.githubusercontent.com/34776946/50776979-5b439300-12d5-11e9-8fcc-c66fc878f315.png)

![9](https://user-images.githubusercontent.com/34776946/50776998-5f6fb080-12d5-11e9-9d8f-6f72cf9885ff.png)

I searched "netlogo" or "link" and find nothing.

**Comment by quaquel** [comment] 2019-01-07 15:40
what is in include?

**Comment by Westlife1002** [comment] 2019-01-07 15:41
![0](https://user-images.githubusercontent.com/34776946/50777152-c3927480-12d5-11e9-9bd7-390fc44e8786.png)

**Comment by quaquel** [comment] 2019-01-07 15:42
can you search in the build directory to see if netlogolink.jar is there?

**Comment by Westlife1002** [comment] 2019-01-07 15:44
no, it's not in both folders. Is it possible to manually add it but I dont know where to place it.

**Comment by quaquel** [comment] 2019-01-07 15:47
If you now run your exe, according to the print statement, where is pyNetLogo expecting the file?

**Comment by Westlife1002** [comment] 2019-01-07 15:49
![000](https://user-images.githubusercontent.com/34776946/50777510-c6419980-12d6-11e9-8d34-d150c50711b7.png)

**Comment by quaquel** [comment] 2019-01-07 15:50
ok, so the file is expected in \py\NetLogo\java, you could manually copy it there just to get it working

**Comment by Westlife1002** [comment] 2019-01-07 15:58
Great! It's working now. I have to copy the entire PyNetlogo folder rather than Netlogolink.jar into the dist folder. Thank you
![777](https://user-images.githubusercontent.com/34776946/50778091-19681c00-12d8-11e9-9717-2849b5d3c223.png)

**Comment by Westlife1002** [comment] 2019-01-07 16:09
If the same logic applies , I guess I should copy the PyNetlogo folder to another required path (shown below) if I want to build in one file (-F)

![1](https://user-images.githubusercontent.com/34776946/50778710-9c3da680-12d9-11e9-82a5-77f748ebb197.png)

**Comment by quaquel** [comment] 2019-01-07 16:30
That won't work. The file uses a temporary directory.

**Comment by Westlife1002** [comment] 2019-01-08 03:18
I will check with Pyinstaller community about how to include the folder using -onefile option. Do you have a solution in your mind? thanks

**Comment by quaquel** [comment] 2019-01-08 07:41
I would start with figuring out how to make it work with a directory structure without having to copy the files. Only once this works, you might try seeing if this also fixes the single file problem. My reading of the pyinstaller documentation is that this is the suggested approach: always first make it work with a directory structure.

**Closed by quaquel** 2019-01-08 07:41 UTC
